version: '3'

# Php-fpm configuration
  php:
    build: ./php_docker/
    volumes:
      - .:/app/public
    links:
      - clubdb

  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/app/public
    links:
      - php
    depends_on:
      - php
