
# Php-fpm configuration
services:
  php-panda:
    build: ./php_docker/
    environment:
      CLUB_PANDA_DB_PATH: /app/data/clubpanda.sqlite
    volumes:
      - .:/app/public
      - ../clubpanda.sqlite:/app/data/clubpanda.sqlite
    networks:
      - panda-net

  web-panda:
    build: .
    ports:
      - "5000:80"
    volumes:
      - .:/app/public
    depends_on:
      - php-panda
    networks:
      - panda-net

networks:
  panda-net:
    driver: bridge
