
# Php-fpm configuration
services:
  php-panda:
    build: ./php_docker/
    volumes:
      - .:/app/public
    networks:
      - panda-net

  web-panda:
    build: .
    ports:
      - "5000:80"
    volumes:
      - .:/app/public
    depends_on:
      - php-panda
    networks:
      - panda-net

networks:
  panda-net:
    driver: bridge
